.DE Ip
.BR
.IE \\n.$>=3 .ne \\$3
.EL .ne 3
.IP "\\$1" \\$2
..
.\"
.\"
.TH COMPILER488 1 "4 February 1999" "CSC488S Compiler"
.SH NAME
compiler488 \- a compiler for the CSC 488S Project Language
.SH SYNOPSIS
.IN +\w'\fBcompiler488 \fR'u
.TI -\w'\fBcompiler488 \fR'u
.B compiler488\ 
[ \fB\-X\fR\ ]
[ \fB\-D\fR[\fIabxy\fR] ]
[ \fB\-T\fR[\fIacilpsxy\fR] ]
[ \fB\-O\fR\ \fIoutputFilename\fR\ ]
[ \fB\-E\fR\ \fIerrorFilename\fR\ ]
[ \fB\-R\fR\ \fItraceFilename\fR\ ]
[ \fB\-U\fR\ \fIdumpFilename\fR\ ]
[ \fB\-I\fR\ \fIrunInputFilename\fR\ ]
[ \fI\ sourceFile\ \fR\ ]
.SH DESCRIPTION
.B compiler488
is an incredibly well designed and implemented compiler for the
CSC488S Course Project Language.
.PP
The compiler compiles and then attempts to execute one program
written in the CSC488S Project Language.
The compiler reads the source program from \fIsourceFile\fR
if it was specified in the command that invoked the compiler.
Otherwise it exepcts the source program on standard input.
.SH OPTIONS
The options currently implemented by the
compiler488 are:
.TP 12
.BR \-X
Suppress execution of the compiled program.  Saves time when testing
an incomplete code generator.
.TP
.BR \-D
Specify dump options.  The letters \fIabxy\fR indicate which information
should be dumped to the compilers \fIdumpFile\fR.
.RS
\fIa\fR \- dump Abstract Syntax Tree after Pass 1
.BR
\fIb\fR \- dump Abstract Syntax Tree after Pass 2
.BR
\fIx\fR \- dump the compiled code just before execution
.BR
\fIy\fR \- dump symbol table information
.RE
.TP
.BR \-T
Specify trace options.  The letters \fIacilpsxy\fR indicate which trace
information
should be written to the compilers \fItraceFile\fR.
.RS
\fIa\fR \- trace Abstract Syntax Tree operations
.BR
\fIc\fR \- trace code generation
.BR
\fIi\fR \- trace source program input in the scanner
.BR
\fIl\fR \- trace tokens in lexical analysis
.BR
\fIp\fR \- trace parsing
.BR
\fIs\fR \- trace semantic analysis
.BR
\fIx\fR \- trace program execution
.BR
\fIy\fR \- trace symbol table operations
.RE
.TP 12
.BR \-E \ \ \ \fIerrorFile\fR
Specify an alternative file to receive error messages generated by the compiler.
Default for error messages is stderr.
.TP
.BI \-O \ \ \ \fIoutputFileName\fR
Specify an alternative file to receive ordinary compiler output (includes
compilation and execution). Default for compiler output is stdout.
.TP
.BR \-R \ \ \ \fItraceFileName\fR
Specify an alternative file to receive compiler trace informantion.
Default for trace information is stdout.
.TP
.BR \-U \ \ \ \fIdumpFileName\fR
Specify an alternative file to receive compiler dump information.
Default for dump information is stdout.
.TP
.BR \-I \ \ \ \fIrunInputFileName\fR
Specify an alternative file to serve as a source of input during
execution of the compiled program.
Default for execution time input is stdin.
.SH ENVIRONMENT
The compiler does not use any Unix environment variables.
.SH SEE ALSO
The CSC488S course news group 
.CW
ut.cdf.csc488h
.SH AUTHORS
The 
.B compiler488
skeleton was conceived and implemented by Profs. David B. Wortman
(machine interpreter and general structure)
and Marsha Chechik (scanner).  
.PP
Parse tree creation, semantic analysis, code generation and the 
symbol table mechanisms
were skillfully designed and implemented by 
.B PUT YOUR NAMES HERE
.SH BUGS
There are none; only a few unexpected features.
